### ISSUE TITLE
Issues when using untis4j on android

### ISSUE THREAD

**Issue by TheGreyDiamond** [ByteDream/untis4j#7]
When trying to use `session.getTimetable(start, end, UntisUtils.ElementType.CLASS, cl.getId());` I get this stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    Process: de.thegreydiamond.wearuntis, PID: 13430
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;
        at org.bytedream.untis4j.responseObjects.Subjects$SubjectObject.<init>(Subjects.java:229)
        at org.bytedream.untis4j.Session.lambda$11(Session.java:562)
        at org.bytedream.untis4j.Session$$ExternalSyntheticLambda21.getResponse(Unknown Source:0)
        at org.bytedream.untis4j.CacheManager.lambda$0$CacheManager(CacheManager.java:58)
        at org.bytedream.untis4j.CacheManager$$ExternalSyntheticLambda0.apply(Unknown Source:15)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1129)
        at org.bytedream.untis4j.CacheManager.getOrRequest(CacheManager.java:66)
        at org.bytedream.untis4j.Session.requestSender(Session.java:160)
        at org.bytedream.untis4j.Session.requestSender(Session.java:137)
        at org.bytedream.untis4j.Session.getSubjects(Session.java:531)
        at org.bytedream.untis4j.Session.lambda$15$Session(Session.java:714)
        at org.bytedream.untis4j.Session$$ExternalSyntheticLambda17.getResponse(Unknown Source:2)
        at org.bytedream.untis4j.CacheManager.lambda$0$CacheManager(CacheManager.java:58)
        at org.bytedream.untis4j.CacheManager$$ExternalSyntheticLambda0.apply(Unknown Source:15)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1129)
        at org.bytedream.untis4j.CacheManager.getOrRequest(CacheManager.java:66)
        at org.bytedream.untis4j.Session.requestSender(Session.java:160)
        at org.bytedream.untis4j.Session.getTimetable(Session.java:701)
        at de.thegreydiamond.wearuntis.MainActivity$3.run(MainActivity.java:84)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.Color" on path: DexPathList[[dex file "/data/data/de.thegreydiamond.wearuntis/code_cache/.overlay/base.apk/classes.dex", dex file "/data/data/de.thegreydiamond.wearuntis/code_cache/.overlay/base.apk/classes3.dex", dex file "/data/data/de.thegreydiamond.wearuntis/code_cache/.overlay/base.apk/classes4.dex", zip file "/data/app/~~mHyames2SehhIxcJ0quf-w==/de.thegreydiamond.wearuntis-fYGCuT9xEX2DExvtgQnHbA==/base.apk"],nativeLibraryDirectories=[/data/app/~~mHyames2SehhIxcJ0quf-w==/de.thegreydiamond.wearuntis-fYGCuT9xEX2DExvtgQnHbA==/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.bytedream.untis4j.responseObjects.Subjects$SubjectObject.<init>(Subjects.java:229) 
        at org.bytedream.untis4j.Session.lambda$11(Session.java:562) 
        at org.bytedream.untis4j.Session$$ExternalSyntheticLambda21.getResponse(Unknown Source:0) 
        at org.bytedream.untis4j.CacheManager.lambda$0$CacheManager(CacheManager.java:58) 
        at org.bytedream.untis4j.CacheManager$$ExternalSyntheticLambda0.apply(Unknown Source:15) 
        at java.util.HashMap.computeIfAbsent(HashMap.java:1129) 
        at org.bytedream.untis4j.CacheManager.getOrRequest(CacheManager.java:66) 
        at org.bytedream.untis4j.Session.requestSender(Session.java:160) 
        at org.bytedream.untis4j.Session.requestSender(Session.java:137) 
        at org.bytedream.untis4j.Session.getSubjects(Session.java:531) 
        at org.bytedream.untis4j.Session.lambda$15$Session(Session.java:714) 
        at org.bytedream.untis4j.Session$$ExternalSyntheticLambda17.getResponse(Unknown Source:2) 
        at org.bytedream.untis4j.CacheManager.lambda$0$CacheManager(CacheManager.java:58) 
        at org.bytedream.untis4j.CacheManager$$ExternalSyntheticLambda0.apply(Unknown Source:15) 
        at java.util.HashMap.computeIfAbsent(HashMap.java:1129) 
        at org.bytedream.untis4j.CacheManager.getOrRequest(CacheManager.java:66) 
        at org.bytedream.untis4j.Session.requestSender(Session.java:160) 
        at org.bytedream.untis4j.Session.getTimetable(Session.java:701) 
        at de.thegreydiamond.wearuntis.MainActivity$3.run(MainActivity.java:84) 
        at java.lang.Thread.run(Thread.java:923) 

```
It seems like java.awt.Color is not supported on android. I tried patching this out in my own branch but I ran into a huge pile of issues and gave up on that (I had issues with mismatching class versions, missing forEach functions).
I would really appriciate some help on how to use it anyways.

**Comment by ByteDream** [comment]
Which android version are you using?

**Comment by TheGreyDiamond** [comment]
Thanks! I was trying to build a Wear os untis app

**Comment by ByteDream** [comment]
I've created an [Android](https://github.com/ByteDream/untis4j/tree/android) branch for this issue which replaces `awt.Color` with simple hex strings (e.g. `#000000`). I've created a jar files for android too, they're available as asset from the [latest release](https://github.com/ByteDream/untis4j/releases/tag/v1.2.1). I hope they are working fine on android, I currently have no testing capacities to check if it runs on android.

**Comment by TheGreyDiamond** [comment]
Hey! I managed to try out your new release. The example "Find / search a specific class", wroks. but I did that before. However "Simple timetable" does not work. This exception gets thrown:
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: de.thegreydiamond.testuntis, PID: 14499
    java.lang.NoSuchMethodError: No virtual method forEach(Ljava/util/function/Consumer;)V in class Lorg/json/JSONArray; or its super classes (declaration of 'org.json.JSONArray' appears in /apex/com.android.art/javalib/core-libart.jar)
        at org.bytedream.untis4j.Session.lambda$15$Session(Session.java:735)
        at org.bytedream.untis4j.Session$$ExternalSyntheticLambda17.getResponse(Unknown Source:2)
        at org.bytedream.untis4j.CacheManager.lambda$0$CacheManager(CacheManager.java:58)
        at org.bytedream.untis4j.CacheManager$$ExternalSyntheticLambda0.apply(Unknown Source:15)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1129)
        at org.bytedream.untis4j.CacheManager.getOrRequest(CacheManager.java:66)
        at org.bytedream.untis4j.Session.requestSender(Session.java:160)
        at org.bytedream.untis4j.Session.getTimetable(Session.java:701)
        at org.bytedream.untis4j.Session.getTimetableFromClassId(Session.java:828)
        at de.thegreydiamond.testuntis.MainActivity$1.run(MainActivity.java:39)
        at java.lang.Thread.run(Thread.java:923)
I/Process: Sending signal. PID: 14499 SIG: 9
```
Here is my current code: https://gist.github.com/TheGreyDiamond/61a679112cfa7cee153bdfb910e4dca4

I have no real idea why this fails.

**Comment by ByteDream** [comment]
Does your android version support the stream api which was introduced in java 8?

If yes, something like this should work:
```java
int[] test = {1, 2, 3};
Arrays.asList(test).forEach(i -> System.out.println(i));
```

**Comment by TheGreyDiamond** [comment]
It should™️  run Java 11, I tried your little example and got this output from it: 
```
I/System.out: ----------------------
    [I@839ab9b
```
(I've added a `System.out.println("----------------------");` before it)

**Comment by ByteDream** [comment]
Hm probably yes. If you are using the jar with dependencies included, try the one without the dependencies and include the org.json library manually

**Comment by TheGreyDiamond** [comment]
I tried it just now and it doesn't seem to fix it.

**Comment by ByteDream** [comment]
It seems like that `org.json` is included in the android core library and cannot be "replaced" with an external, newer (or one which supports the stream api), org.json library

**Comment by TheGreyDiamond** [comment]
Oh, that sucks. Is there a drop in replacement which has the needed features but needs minimal / no code editing? I'm not really that much into Jaava that's why I have to ask 😅

**Comment by ByteDream** [comment]
I've created a patched android build without the stackoverflow workaround you provided (I saw your edit too late lol). It can be downloaded from the [latest release](https://github.com/ByteDream/untis4j/releases/tag/v1.2.1)

**Comment by TheGreyDiamond** [comment]
Okay, I'll try it once again. Let's see if it works!

**Comment by TheGreyDiamond** [comment]
It seems to work! Thank you soo much, if anything else breaks under android, I'll let you know!
